# Generated by Django 4.2.9 on 2026-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementpost",
            name="min_cgpa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
